### PR TITLE
[CI] Download just `gen_stub.php` script instead of the whole PHP source

### PR DESCRIPTION
**Pull request by phansys**

### CODE REVIEW

**Comment by NattyNarwhal** [comment]
LGTM and checks pass, though I wonder if we should also be fetching PhpParser in CI too. We're relying on `gen-stub.php`'s `installPhpParser` function, and while that does the right thing, it is surprising to have it download every time. Our CI isn't as strict as a Linux distro, so maybe explicitly fetching from PEAR or whatever isn't worth it.

We also cache the other resources, but gen-stub is really small.

**Comment by phansys** [comment]
Let me check what can I do about the explicit install and the caching.

**Comment by NattyNarwhal** [comment]
FWIW, caching is somewhat flaky - until recently I wasn't able to get the driver and container caching working reliable until it started working by itself. :shrug: The fact it's also fetching from GitHub internally might also be a big deal performance wise; I would hope the CI servers have a fast connection to GitHub.

**Comment by phansys** [comment]
Checking the behavior at [`gen-stub.php`](https://github.com/php/php-src/blob/70ee6c20ad97e02c2b8098aeea96fefbbc3ac5c2/build/gen_stub.php#L4597-L4608) I see the path, the version and the classes autoload are determined by `initPhpParser()`:
```php
$version = "4.15.1";
$phpParserDir = __DIR__ . "/PHP-Parser-$version";
if (!is_dir($phpParserDir)) {
    installPhpParser($version, $phpParserDir);
}

spl_autoload_register(static function(string $class) use ($phpParserDir) {
    if (strpos($class, "PhpParser\\") === 0) {
        $fileName = $phpParserDir . "/lib/" . str_replace("\\", "/", $class) . ".php";
        require $fileName;
    }
});
```

So, IMO, we leave this kinda hardcoded because there is no chance to change the version or path through some inference or parameterizing.

**Comment by NattyNarwhal** [comment]
LGTM. The bit about PhpParser is unfortunate, but maybe over time the tooling will improve there.

**Pull request merged**
