### PR TITLE
Leverage GitHub actions services instead of manually running the "ibmcom/db2" container

### PR DESCRIPTION
**Pull request by phansys**
See https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices.

### CODE REVIEW

**Comment by NattyNarwhal** [comment]
This makes a lot of sense to me.

Amusingly, I checked PHP upstream's usage and they do seem to use this for MySQL, but not for MSSQL or Oracle.

I assume since the service is starting while the extension builds, we have some leeway with timing, but I noticed we aren't blocking on it anymore, instead just checking. Seems racy maybe?

**Comment by phansys** [comment]
I assume since the service is starting while the extension builds, we have some leeway with timing, but I noticed we aren't blocking on it anymore, instead just checking. Seems racy maybe?

The job "Perform healthcheck on db2 service" is ensuring the service availability. The `docker logs -f` command is producing a stream that is used to detect the presence of the "Setup has completed" string in the output before proceeding to the subsequent jobs.

**Comment by NattyNarwhal** [comment]
> The job "Perform healthcheck on db2 service" is ensuring the service availability. The docker logs -f command is producing a stream that is used to detect the presence of the "Setup has completed" string in the output before proceeding to the subsequent jobs.

Oh, I didn't notice the `-f` there. That's better than the busy loop from before then.

**Comment by phansys** [comment]
I've pushed a new commit leveraging the built-in Docker health check options.

**Pull request merged**
