### PR TITLE
Update README.md to have pre-requisite info.

### PR DESCRIPTION
**Pull request by praveen-db2**
Hi @NattyNarwhal,

Can we update readme as I proposed here, I just added an extra pre-requisite para, most of our DB2 connect customers ask for this info.

Your suggestions to my changes are welcome.

### CODE REVIEW

**Comment by praveen-db2** [comment]
@NattyNarwhal can you pls consider this on priority.

**Comment by kadler** [comment]
Requiring PHP seems pretty obvious to me, so I'm not sure why that's needed to be stated.

Having a statement of which PHP versions are supported seems beneficial.

**Comment by praveen-db2** [comment]
@NattyNarwhal  Its standard statement we are using across diff drivers like for python, ruby, go etc... We want to maintain the same. Its obvious for experienced developers, for new developers its better to have.

**Comment by NattyNarwhal** [comment]
I'd say we support 7.3 still (it's the minreq in `package.xml`, plus we use 7.3+ APIs), but I wouldn't be opposed to only supporting releases upstream PHP supports.

**Comment by praveen-db2** [comment]
@NattyNarwhal yes we better specify only supported PHP releases.

**Comment by praveen-db2** [comment]
@kadler @NattyNarwhal I had changed statement as you suggested. Request to review and merge.

**Pull request merged**
