### PR TITLE
Use camel case for parameter names in `ibm_db2.stub.php`

### PR DESCRIPTION
**Pull request by phansys**
The parameter `$colnum` in `db2_lob_read()` was also renamed to `$columnNumber`;

**TODO**:
- [x] Wait for #32.

### CODE REVIEW

**Review by tessus — COMMENTED** [review]
I think we always used underscores in ibmdb2. But in reality it doesn't matter as long as it is consistent. I defer judgement to the devs who took this over.

**Comment by phansys** [comment]
I understand. I'm proposing this change because I saw the camel case as the most used style in modern PHP libraries. Also, it is already used in other extensions (like [PDO](https://www.php.net/manual/en/pdostatement.fetch.php), by instance).
By other hand, the casing is actually different between the base (English) documentation and other translations:
* EN: https://github.com/php/doc-en/blob/38785e987736461dd63952c887e2079a83187ba4/reference/ibm_db2/functions/db2-bind-param.xml#L16 (camel case);
* ES: https://github.com/php/doc-es/blob/d520c68797f6f3feb82746a191ffa2a645ae21cb/reference/ibm_db2/functions/db2-bind-param.xml#L17 (kebab case).

**Comment by NattyNarwhal** [comment]
I'm also fine with doing whatever as long as it's consistent.

**Comment by phansys** [comment]
I decided to close this PR by now, as I confirmed that the stub generates the proper documentation using underscores. The lack of consistency between translations seems to be a human mistake.
Given that there are many tools relying on the names of the current parameters, I think there is no great gain with this change.

Thank you!

**Pull request closed without merging**
