### PR TITLE
[CI] Check that headers are up to date in the CI pipeline

### PR DESCRIPTION
**Pull request by phansys**
**TODO**:
- [x] Wait for #32.

### CODE REVIEW

**Comment by Girgias** [comment]
This PR looks completely nonsensical, you are using a documentation flag for something that doesn't seem to do any comparison to docs.

If what you are after is checking that the arginfos are correctly generated than copy part of https://github.com/php/php-src/blob/master/.github/actions/verify-generated-files/action.yml

**Comment by phansys** [comment]
>This PR looks completely nonsensical, you are using a documentation flag for something that doesn't seem to do any comparison to docs.

The intention of this PR is checking if the contents in `ibm_db2.stub.php` produces any change in `ibm_db2_arginfo.h` or `ibm_db2_legacy_arginfo.h`.
The resulting XML documenaton is not under the SCM in this repo, so there is no check against those files here.

Please, let me know if I am misunderstanding the purpose of `ibm_db2_arginfo.h` and `ibm_db2_legacy_arginfo.h`. To me, given the way they are currently generated by `gen_stub.php`, they seem an artifact that must be in sync with its source (`ibm_db2.stub.php`).

**Comment by phansys** [comment]
@Girgias, sorry for the ping.

I've removed the `--replace-methodsynopses` option from the `gen_stub.php` execution. Could you please confirm it it makes sense for you?
Thank you in advance.

**Comment by Girgias** [comment]
Looks fine to me now.

**Pull request merged**
